version: "2"
services:
  jenkins:
    container_name: my_jenkins
    build: ./services/jenkins/
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/docker/jenkins:/var/jenkins_home"
    environment:
      http_proxy: "${http_proxy}"
  gitlab:
    container_name: my_gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - "8081:80"
      - "8084:443"
    environment:
      http_proxy: "${http_proxy}"
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'Welcome#1'
        unicorn['worker_processes'] = 10
        unicorn['worker_timeout'] = 120
    volumes:
      - "/srv/docker/gitlab/config:/etc/gitlab"
      - "/srv/docker/gitlab/logs:/var/log/gitlab"
      - "/srv/docker/gitlab/data:/var/opt/gitlab"
  redmine_mysql:
    container_name: my_redmine_mysql
    image: mysql:5.7.17
    restart: always
    environment:
      http_proxy: "${http_proxy}"
      MYSQL_ROOT_PASSWORD: "Welcome#1"
      MYSQL_DATABASE: "redmine"
      MYSQL_USER: "redmine"
      MYSQL_PASSWORD: "Welcome#1"
    volumes:
      - "/srv/docker/redmine/mysql:/var/lib/mysql"
  redmine:
    container_name: my_redmine
    image: redmine:3.3.2
    restart: always
    ports:
      - "8082:3000"
    links:
      - redmine_mysql:mysql
    depends_on:
      - redmine_mysql
    environment:
      http_proxy: "${http_proxy}"
      REDMINE_DB_PASSWORD: "Welcome#1"
      REDMINE_DB_MYSQL: "mysql"
      REDMINE_DB_DATABASE: "redmine"
    volumes:
      - /srv/docker/redmine/redmine:/home/redmine/data

  nginx:
    build: ./services/nginx
    links:
      - jenkins:jenkins
      - redmine:redmine
      - gitlab:gitlab
    ports:
      - 80:80
