version: "2"
services:
  jenkins:
    container_name: my_jenkins
    build:
      context: ./services/jenkins/
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${http_proxy}"      
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/jenkins:/var/jenkins_home
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${http_proxy}"
      HTTP_PROXY: "${http_proxy}"
      HTTPS_PROXY: "${http_proxy}"
      no_proxy: "gitlab,jenkins,rocketchat,redmine"
      NO_PROXY: "gitlab,jenkins,rocketchat,redmine"
      JAVA_OPTS: |
         -Dhttp.proxyHost="${http_proxy_host}"
         -Dhttp.proxyPort="${http_proxy_port}"
      JENKINS_OPTS: |
        --prefix=/jenkins
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    ports:
      - 8081:80
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${http_proxy}"
      HTTP_PROXY: "${http_proxy}"
      HTTPS_PROXY: "${http_proxy}"
      no_proxy: "gitlab,jenkins,rocketchat,redmine"
      NO_PROXY: "gitlab,jenkins,rocketchat,redmine"
      GITLAB_RELATIVE_URL_ROOT: /gitlab
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:80/gitlab'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'Welcome#1'
        unicorn['worker_processes'] = 10
        unicorn['worker_timeout'] = 120
    volumes:
      - /srv/docker/gitlab/config:/etc/gitlab
      - /srv/docker/gitlab/logs:/var/log/gitlab
      - /srv/docker/gitlab/data:/var/opt/gitlab
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
      DB_USER: redmine
      DB_PASS: password
      DB_NAME: redmine_production
    volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql
  redmine:
    image: sameersbn/redmine:3.3.2-1
    depends_on:
    - postgresql
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${http_proxy}"
      HTTP_PROXY: "${http_proxy}"
      HTTPS_PROXY: "${http_proxy}"
      TZ: Asia/Kolkata
      DB_ADAPTER: postgresql
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: redmine
      DB_PASS: password
      DB_NAME: redmine_production
      REDMINE_HTTPS: "false"
      REDMINE_RELATIVE_URL_ROOT: /redmine
      REDMINE_SECRET_TOKEN:
      REDMINE_SUDO_MODE_ENABLED: "false"
      REDMINE_SUDO_MODE_TIMEOUT: 15
      REDMINE_CONCURRENT_UPLOADS: 2
      REDMINE_BACKUP_SCHEDULE: 
      REDMINE_BACKUP_EXPIRY: 
      REDMINE_BACKUP_TIME: 
    ports:
      - "8082:80"
    volumes:
      - /srv/docker/redmine/redmine:/home/redmine/data
  rocketchat:
    image: rocketchat/rocket.chat
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${http_proxy}"
      HTTP_PROXY: "${http_proxy}"
      HTTPS_PROXY: "${http_proxy}"
      no_proxy: "gitlab,jenkins,rocketchat,redmine"
      NO_PROXY: "gitlab,jenkins,rocketchat,redmine"
      ROOT_URL: http://localhost:3000/rocketchat
      MONGO_URL: mongodb://mongodb/rocketchat
    links:
      - mongodb
    ports:
      - 8083:3000
  mongodb:
    image: mongo
    ports:
       - 27017
    volumes:
      - /srv/docker/rocketchat/mongodb:/data/db
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    links:
      - jenkins:jenkins
      - redmine:redmine
      - gitlab:gitlab
      - rocketchat:rocketchat
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
