version: '2'
services:
  jenkins:
    container_name: my_jenkins
    build: ./services/jenkins/
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    volumes_from:
      - jenkins_data
  jenkins_data:
    container_name: my_jenkins_data
    image: devopsbydocker_jenkins
  gitlab-mysql:
    container_name: my_gitlab_mysql
    image: sameersbn/mysql:latest
    environment:
      - DB_USER=gitlab
      - DB_PASS=Welcome#1
      - DB_NAME=gitlabhq_production
  gitlab:
    container_name: my_gitlab
    image: sameersbn/gitlab:8.0.4
    links:
      - gitlab-redis:redisio
      - gitlab-mysql:mysql
    ports:
      - "10080:80"
      - "10022:22"
    environment:
      http_proxy: "${http_proxy}"
      DEBUG: "false"
      TZ: Asia/Tokyo
      GITLAB_TIMEZONE: Tokyo
      GITLAB_SECRETS_DB_KEY_BASE: long-and-random-alphanumeric-string
      GITLAB_HOST: localhost
      GITLAB_PORT: 10080
      GITLAB_SSH_PORT: 10022
      GITLAB_NOTIFY_ON_BROKEN_BUILDS: "true"
      GITLAB_NOTIFY_PUSHER: "false"
      GITLAB_EMAIL: notifications@example.com
      GITLAB_EMAIL_REPLY_TO: noreply@example.com
      GITLAB_INCOMING_EMAIL_ADDRESS: reply@example.com
      GITLAB_BACKUPS: daily
      GITLAB_BACKUP_TIME: 01:00
      SMTP_ENABLED: "false"
      SMTP_DOMAIN: www.example.com
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: mailer@example.com
      SMTP_PASS: password
      SMTP_STARTTLS: "true"
      SMTP_AUTHENTICATION: login
      IMAP_ENABLED: "false"
      IMAP_HOST: imap.gmail.com
      IMAP_PORT: 993
      IMAP_USER: mailer@example.com
      IMAP_PASS: password
      IMAP_SSL: "true"
      IMAP_STARTTLS: "false"
  gitlab-redis:
    container_name: my_gitlab_redis
    image: sameersbn/redis:latest
    environment:
      http_proxy: "${http_proxy}"
  redmine:
    container_name: my_redmine
    image: redmine:3.3.2
    restart: always
    ports:
      - "8082:3000"
    links:
      - redmine-mysql:mysql
    depends_on:
      - redmine-mysql
    environment:
      http_proxy: "${http_proxy}"
      MYSQL_ROOT_PASSWORD: Welcome#1
      REDMINE_DB_MYSQL: redmine-mysql
    volumes_from:
      - redmine_data
  redmine_data:
    container_name: my_redmine_data
    image: redmine:3.3.2
  redmine-mysql:
    container_name: my_redmine_mysql
    image: mysql:5.7.17
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Welcome#1
      MYSQL_DATABASE: redmine
  redmine-mysql-data:
    container_name: my_redmine_mysql_data
    image: redmine:3.3.2
