version: '2'
services:
  jenkins:
    container_name: my_jenkins
    build: ./services/jenkins/
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    volumes_from:
      - jenkins_data
  jenkins_data:
    container_name: my_jenkins_data
    image: devopsbydocker_jenkins

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.16.4
    links:
      - gitlab-redis:redisio
      - gitlab-mysql:mysql
    environment:
      http_proxy: "${http_proxy}"
      DEBUG: false
      TZ: Asia/Tokyo
      GITLAB_TIMEZONE: Tokyo
      GITLAB_SECRETS_DB_KEY_BASE: long-and-random-alphanumeric-string
      GITLAB_NOTIFY_ON_BROKEN_BUILDS: true
      GITLAB_EMAIL: hironori.tamakoshi@oracle.com
      GITLAB_EMAIL_REPLY_TO: noreply@example.com
      GITLAB_INCOMING_EMAIL_ADDRESS: reply@example.com
  gitlab-mysql:
    restart: always
    image: sameersbn/mysql:latest
    environment:
      DB_USER: gitlab
      DB_PASS: Welcome#1
      DB_NAME: gitlab
  gitlab-redis:
    restart: always
    image: sameersbn/redis:latest

  redmine:
    container_name: my_redmine
    image: redmine:3.3.2
    restart: always
    ports:
      - "8082:3000"
    links:
      - redmine-mysql:mysql 
    depends_on:
      - redmine-mysql
    environment:
      http_proxy: "${http_proxy}"
      MYSQL_ROOT_PASSWORD: Welcome#1
      REDMINE_DB_MYSQL: redmine-mysql
    volumes_from:
      - redmine-data
  redmine_data:
    container_name: my_redmine_data
    image: redmine:3.3.2
  redmine-mysql:
    container_name: my_redmine_mysql
    image: mysql:5.7.17
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Welcome#1
      MYSQL_DATABASE: redmine
  redmine-mysql-data:
    container_name: my_redmine_mysql_data
    image: redmine:3.3.2